// Generated by gencpp from file info_test/speed.msg
// DO NOT EDIT!


#ifndef INFO_TEST_MESSAGE_SPEED_H
#define INFO_TEST_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace info_test
{
template <class ContainerAllocator>
struct speed_
{
  typedef speed_<ContainerAllocator> Type;

  speed_()
    : header()
    , mode(0)
    , speed(0)  {
    }
  speed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _mode_type;
  _mode_type mode;

   typedef int16_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::info_test::speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::info_test::speed_<ContainerAllocator> const> ConstPtr;

}; // struct speed_

typedef ::info_test::speed_<std::allocator<void> > speed;

typedef boost::shared_ptr< ::info_test::speed > speedPtr;
typedef boost::shared_ptr< ::info_test::speed const> speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::info_test::speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::info_test::speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::info_test::speed_<ContainerAllocator1> & lhs, const ::info_test::speed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mode == rhs.mode &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::info_test::speed_<ContainerAllocator1> & lhs, const ::info_test::speed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace info_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::info_test::speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::info_test::speed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::info_test::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::info_test::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::info_test::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::info_test::speed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::info_test::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69015ee51544e9edc0fbdcc4576063cb";
  }

  static const char* value(const ::info_test::speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69015ee51544e9edULL;
  static const uint64_t static_value2 = 0xc0fbdcc4576063cbULL;
};

template<class ContainerAllocator>
struct DataType< ::info_test::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "info_test/speed";
  }

  static const char* value(const ::info_test::speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::info_test::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int16 mode\n"
"int16 speed\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::info_test::speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::info_test::speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::info_test::speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::info_test::speed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mode);
    s << indent << "speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFO_TEST_MESSAGE_SPEED_H
